# Generated by Django 4.1.5 on 2023-01-09 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название теста или его номер', max_length=200, verbose_name='Название теста')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Введите вопрос', verbose_name='Текст вопроса')),
                ('correct_answer_count', models.SmallIntegerField(help_text='Введите количество правильных ответов у этого вопроса', verbose_name='Количество правильных ответов')),
                ('test', models.ManyToManyField(related_name='Question', to='rus_lang_ege.test')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_class', models.CharField(help_text='Введите класс или экзамен', max_length=150, verbose_name='Номер класса')),
                ('test', models.ManyToManyField(related_name='level', to='rus_lang_ege.test')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(help_text='Количество правильных ответов за тест', verbose_name='Количество правильных ответов')),
                ('conclusion', models.CharField(choices=[('5', 'Все супер'), ('4', 'Ошибки есть,но все-равно молодец'), ('3', 'Надо приложить усилия для изучения этой темы')], max_length=50, verbose_name='заключение')),
                ('finished_at', models.DateTimeField(auto_now_add=True, verbose_name='Время окончания теста')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rus_lang_ege.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(help_text='Введите вариант ответа', max_length=256, verbose_name='Ответ')),
                ('is_right', models.BooleanField(help_text='Отметьте, если ответ правильный', verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rus_lang_ege.question')),
            ],
        ),
    ]
