# Generated by Django 4.1.5 on 2023-01-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rus_lang_ege', '0002_alter_answer_options_alter_examresult_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='grade',
            field=models.ForeignKey(default=1, help_text='Вы не можете удалить класс,пока у него есть тесты', on_delete=django.db.models.deletion.PROTECT, to='rus_lang_ege.level', verbose_name='Класс'),
            preserve_default=False,
        ),
    ]
